### ISSUE TITLE
QQ截图真是个不折不扣的流氓工具

### ISSUE THREAD

**Issue by lovelock** [YJBeetle/kill-QQ-jietu-plugin#1]
首先QQ的快捷键大量和macOS的冲突，尤其是关闭屏幕键，当然QQ用的更早也无可厚非，但后来系统用了这个快捷键，它也不改一下默认。
其次，即便是把QQ的所有快捷键都关掉，它还是会监听Cmd+Ctrl+A这个快捷键，检测到你按了这个就会提示你它需要记录屏幕的权限。。。估计是在QQ截图plugin里面给写死了这个组合键信息。

感谢你这个脚本。不过后面那个权限可能给的不太对，为什么要给`root:wheel`呢？

**Comment by lovelock** [comment]
老哥你的方法不能用了。。。

**Comment by strongbugman** [comment]
哈哈，我这还可以用，另外本身截图的权限就是root:wheel的，所以替换品也一致

**Comment by YJBeetle** [comment]
权限似乎是对的，  首先因为他是在 `/Applications `目录下，其次他原本的的owner也是root，然后就是owner设置为root可以（君子层面的）防止QQ把它偷偷改回来。

**Comment by YJBeetle** [comment]
以及不能用了指的是？我刚又去AppStore上更新了一下QQ 并且再次执行似乎是正常的

**Comment by lovelock** [comment]
> 以及不能用了指的是？我刚又去AppStore上更新了一下QQ 并且再次执行似乎是正常的

AppStore上哪有QQ啊？我是从官网下载的。另外，你是故意要改成root的是吗？我现在也不知道是怎么弄的，有时候打开QQ再想截图它就会一直弹窗提示我要把那个截图工具打开，有时候又没什么事儿，也不知道是啥玩意。我现在把那个文件删掉了

**Comment by lovelock** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/2208731/77733537-fc854900-7041-11ea-89d5-9b8b05e6beed.png">

**Comment by lovelock** [comment]
> 以及不能用了指的是？我刚又去AppStore上更新了一下QQ 并且再次执行似乎是正常的

<img width="904" alt="image" src="https://user-images.githubusercontent.com/2208731/77733861-86cdad00-7042-11ea-8755-5e743b0f6962.png">
我擦，QQ竟然这么靠下，苹果这搜索逻辑也太扯了吧

**Comment by lovelock** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/2208731/77734105-08253f80-7043-11ea-85aa-34557d2d1138.png">

我不得不残酷的告诉你，从AppStore下载的版本直接把快捷键给清除就可以了。就算什么都不做，也只是按了组合键没反应（因为我用的Xnip也是这个组合键，有冲突）
<img width="255" alt="image" src="https://user-images.githubusercontent.com/2208731/77734254-4f133500-7043-11ea-948a-d1bd1c4bfd06.png">

不像腾讯官网下载的版本会弹出上面我说的那个提示。
